# Generated by Django 4.0.4 on 2022-06-15 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
